"""
Django settings for mission_tracker project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Use PyMySQL as MySQL driver (pure Python, no C++ required)
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load Firebase credentials from separate JSON file
import json
FIREBASE_CREDENTIALS_PATH = BASE_DIR / 'firebase-credentials.json'
if FIREBASE_CREDENTIALS_PATH.exists():
    with open(FIREBASE_CREDENTIALS_PATH, 'r') as f:
        FIREBASE_CREDENTIALS = json.load(f)
        FIREBASE_SERVICE_ACCOUNT_KEY = json.dumps(FIREBASE_CREDENTIALS)
        FIREBASE_PROJECT_ID = FIREBASE_CREDENTIALS.get('project_id', 'bossin-1fabd')
else:
    FIREBASE_CREDENTIALS = None
    FIREBASE_SERVICE_ACCOUNT_KEY = os.getenv('FIREBASE_SERVICE_ACCOUNT_KEY', '')
    FIREBASE_PROJECT_ID = os.getenv('FIREBASE_PROJECT_ID', 'bossin-1fabd')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = "django-insecure-xe*qu2qv)rn-*1tm5q@e%arir$_^)4x2rjdyf0x3bk9oyxz_lg"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

ALLOWED_HOSTS = ["*"]  # Allow all hosts in development


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.humanize",  # For intcomma and other human-readable filters
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by django-allauth
    "allauth",  # Django allauth
    "allauth.account",  # Django allauth account
    "allauth.socialaccount",  # Django allauth social account
    "allauth.socialaccount.providers.google",  # Google OAuth2 provider
    "tracker",
    "pwa",  # Progressive Web App support
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Required by django-allauth
    "tracker.middleware.TenantMiddleware",  # Multi-tenant support
    "tracker.middleware.StaffOnboardingMiddleware",  # Staff onboarding redirect
    "tracker.middleware.SubscriptionEnforcementMiddleware",  # Enforce subscription after trial
]

ROOT_URLCONF = "mission_tracker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tracker.context_processors.theme_context",  # Multi-tenant theming
                "tracker.context_processors_bossin.bossin_admin_context",  # Bossin Admin Portal
            ],
        },
    },
]

WSGI_APPLICATION = "mission_tracker.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for local development (faster, no connection issues)
# Switch to MySQL in production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MySQL Configuration (for production/PythonAnywhere)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'Bossin$member',   # Your full database name
#         'USER': 'Bossin',           # Your PythonAnywhere username
#         'PASSWORD': 'uscf2025',  # Replace with your actual MySQL DB password
#         'HOST': 'Bossin.mysql.pythonanywhere-services.com',
#         'PORT': '3306',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # This assumes your serviceworker.js and icons are in /home/Bossin/finance-committe-app/static/
]

# For production (collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files (for logo uploads)
# https://docs.djangoproject.com/en/5.2/howto/manage-files/
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Custom error handlers
HANDLER404 = 'tracker.views.custom_404'
HANDLER500 = 'tracker.views.custom_500'


# Session Configuration - 10 minute timeout for security
SESSION_COOKIE_AGE = 600  # 10 minutes in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when browser closes
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request to track activity


# your_project/settings.py

PWA_APP_NAME = 'BossIn'
PWA_APP_DESCRIPTION = "A Mission Finance tracker."
PWA_APP_THEME_COLOR = '#7492b9' # Default organization theme color
PWA_APP_BACKGROUND_COLOR = '#FFFFFF'
PWA_APP_DISPLAY = 'standalone' # Makes it feel more like a native app
PWA_APP_SCOPE = '/' # Defines the scope of your PWA
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/login/'
PWA_APP_STATUS_BAR_COLOR = 'default' # For iOS status bar
PWA_APP_ICONS = [
    {
        'src': '/static/icons/icon-128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/icons/icon-144x144.png',
        'sizes': '144x144'
    },
    {
        'src': '/static/icons/icon-152x152.png',
        'sizes': '152x152'
    },
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/icons/apple-touch-icon (2).png',
        'sizes': '180x180'
    }
]
# PWA_APP_SPLASH_SCREEN is for iOS splash screens (optional)
# PWA_APP_SPLASH_SCREEN = [
#     {
#         'src': '/static/images/splash/iphone5_splash.png',
#         'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
#     },
#     # Add more for different devices
# ]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')

# ============================================================================
# LOGGING CONFIGURATION - For debugging and monitoring
# ============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
        'colored': {
            'format': '%(asctime)s [%(levelname)s] %(name)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        # Django core logging
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django database queries
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Django request/response
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Your app logging
        'tracker': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Middleware logging
        'mission_tracker': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)


# ============================================================================
# DJANGO ALLAUTH CONFIGURATION
# ============================================================================

# Site ID for django-allauth
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Account settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Skip email verification for simplicity
ACCOUNT_SIGNUP_REDIRECT_URL = '/onboarding/financial/'
ACCOUNT_LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = 'tracker.adapters.CustomSocialAccountAdapter'

# Google OAuth2 settings (will be configured in production)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),  # Will be set in environment
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),  # Will be set in environment
        }
    }
}

# Firebase Project ID (extracted from Firebase App ID)
# FIREBASE_PROJECT_ID is now loaded from firebase-credentials.json