# Generated by Django 5.2.3 on 2025-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
