# Generated by Django 5.2.3 on 2025-10-26 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_member_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo (recommended: 200x200px)",
                        null=True,
                        upload_to="org_logos/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon (recommended: 32x32px)",
                        null=True,
                        upload_to="org_favicons/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Primary brand color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#64748b",
                        help_text="Secondary color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "success_color",
                    models.CharField(
                        default="#059669",
                        help_text="Success color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "warning_color",
                    models.CharField(
                        default="#d97706",
                        help_text="Warning color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "danger_color",
                    models.CharField(
                        default="#dc2626",
                        help_text="Danger color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "navbar_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom navbar title (defaults to org name)",
                        max_length=255,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, help_text="Custom footer text"),
                ),
                (
                    "watermark_text",
                    models.CharField(
                        default="Bossin",
                        help_text="Watermark text for reports",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Theme",
                "verbose_name_plural": "Organization Themes",
            },
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("viewer", "Viewer"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["organization", "user"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tracker_org_slug_ea6ee8_idx"),
                    models.Index(
                        fields=["is_active"], name="tracker_org_is_acti_0557a7_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="member",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="tracker.organization",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="tracker.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["organization", "is_active"],
                name="tracker_mem_organiz_82b01c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["organization", "created_at"],
                name="tracker_mem_organiz_64b327_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["organization", "date"], name="tracker_tra_organiz_6e2b20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["organization", "member"], name="tracker_tra_organiz_840e56_idx"
            ),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theme",
                to="tracker.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="tracker.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["organization", "user"], name="tracker_org_organiz_0d9400_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationuser",
            index=models.Index(
                fields=["organization", "role"], name="tracker_org_organiz_1fa194_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together={("organization", "user")},
        ),
    ]
