# Generated by Django 5.2.3 on 2025-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_organizationtheme_organizationuser_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtheme",
            name="default_pledge_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=70000,
                help_text="Default pledge amount for new members (e.g., 70000)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=210000,
                help_text="Target collection amount for the organization (e.g., 210000)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="organizationtheme",
            name="primary_color",
            field=models.CharField(
                default="#7492B9",
                help_text="Primary brand color (hex format)",
                max_length=7,
            ),
        ),
    ]
