# Generated by Django 5.2.3 on 2025-10-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_memberedit log"),
        ("tracker", "0004_organizationtheme_default_pledge_amount_and_more"),
    ]

    operations = []
