# Generated by Django 5.2.3 on 2025-10-29 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_merge_20251028_1902"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "needs_onboarding",
                    models.BooleanField(
                        default=False,
                        help_text="User needs to complete onboarding (email/name collection)",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, help_text="User has completed onboarding"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="User phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="User bio or additional information",
                        null=True,
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True,
                        help_text="Firebase user UID",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Send email notifications"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="Preferred language", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RenameIndex(
            model_name="membereditlog",
            new_name="tracker_mem_organiz_6b2eb0_idx",
            old_name="tracker_mem_organiz_idx",
        ),
        migrations.RenameIndex(
            model_name="membereditlog",
            new_name="tracker_mem_organiz_9521ae_idx",
            old_name="tracker_mem_organiz_member_idx",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
