# Generated by Django 5.2.3 on 2025-11-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_userprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="category",
            field=models.CharField(
                choices=[
                    ("organization", "Organization (Blue)"),
                    ("religious", "Religious Contribution"),
                    ("wedding_sendoff", "Wedding & Sendoff"),
                    ("ceremonies", "Ceremonies (Graduation, Birthday, etc.)"),
                    ("condolence", "Condolence"),
                    ("collection_other", "Collection & Other"),
                ],
                default="organization",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("months", models.PositiveIntegerField(default=1)),
                ("is_trial", models.BooleanField(default=False)),
                ("amount_tzs", models.DecimalField(decimal_places=2, max_digits=12)),
                ("discount_percent", models.PositiveIntegerField(default=0)),
                ("category_snapshot", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reference_note",
                    models.CharField(
                        blank=True,
                        help_text="Payer name/phone or M-Pesa ref",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_requests",
                        to="tracker.organization",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="tracker_pay_organiz_c73422_idx",
                    )
                ],
            },
        ),
    ]
