# Generated by Django 5.2.3 on 2025-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_organization_category_paymentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
