# Generated by Django 5.2.3 on 2025-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_organization_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="staff_comment",
            field=models.TextField(
                blank=True, help_text="Internal note by site staff (Bossin)", null=True
            ),
        ),
    ]
