# Generated by Django 5.2.3 on 2025-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_paymentrequest_staff_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("FREE_TRIAL", "Free Trial"),
                    ("NOT_SUBSCRIBED", "Not Subscribed"),
                    ("SUBSCRIBED", "Subscribed"),
                ],
                default="FREE_TRIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="amount_sent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile_payment", "Mobile Payment"),
                    ("wakala", "Wakala/Agent"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
