# Generated by Django 5.2.3 on 2025-11-05 04:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_organization_subscription_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price_tzs",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19800.00"),
                        help_text="Base monthly subscription price in TZS",
                        max_digits=12,
                    ),
                ),
                (
                    "category_discounts",
                    models.JSONField(
                        default=dict,
                        help_text='Discount percentages per category (e.g., {"religious": 50, "organization": 35})',
                    ),
                ),
                (
                    "mpesa_number",
                    models.CharField(
                        default="68256127", help_text="M-Pesa Lipa Namba", max_length=20
                    ),
                ),
                (
                    "mpesa_account_name",
                    models.CharField(
                        default="MIPT SOFTWARES",
                        help_text="M-Pesa account name",
                        max_length=255,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@bossin.com",
                        help_text="Support contact email",
                        max_length=254,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        help_text="Support phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "backup_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic daily backups"
                    ),
                ),
                (
                    "backup_retention_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days to keep backups"
                    ),
                ),
                (
                    "backup_location",
                    models.CharField(
                        default="backups",
                        help_text="Backup storage location (local path or cloud bucket)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
