# Generated by Django 5.2.3 on 2025-11-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_add_system_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="category",
            field=models.CharField(
                choices=[
                    ("organization", "Organization"),
                    ("religious", "Religious Contribution"),
                    ("wedding_sendoff", "Wedding & Sendoff"),
                    ("ceremonies", "Ceremonies (Graduation, Birthday, etc.)"),
                    ("condolence", "Condolence"),
                    ("collection_other", "Collection & Other"),
                ],
                default="organization",
                max_length=32,
            ),
        ),
    ]
